### ISSUE TITLE
make snapping target more flexible

### ISSUE THREAD

**Issue by bartvde** [planetfederal/usgs#102]
tschaub suggests have a preconfigured list in the client app for now

**Comment by bartvde** [comment]
Hmm not sure what is the best option here, creating a new snapping agent all the time, or reconfiguring an existing snapping agent. It seems both approaches will take work at the gxp level.

**Comment by tschaub** [comment]
Both the SnappingAgent and the FeatureEditor could use work to make things more easily configurable.  To satisfy immediate needs, it should be enough to be able to configure the application with a list of layers for which the snapping control should be active.  There is currently a "query" listener for the nhd-manager FeatureManager (in index.html).  In this same listener, the list of layers could be checked (`["NHDPoint", "NHDFlowline"]`).  If `featureManager.layerRecord.get("name")` is in this list, all of `snappingAgent.controls` should be activated.  Otherwise, all should be deactivated.

We'll probably want a better solution than this in the near future, but I think this should be a quick way to disable snapping for all except a limited list of layers.

**Comment by bartvde** [comment]
Ah right, I thought we needed to have more than 1 snapping target, depending on the layer selected. But this simplifies things a lot, i.e. having only 1 snapping target, and having it on or off.
