### ISSUE TITLE
limit FCode/FType options depending on feature type

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#13]
The attribute editing forms should display a limited set of FCode/FType values depending on the feature type.  We need to find (or create) a list of FCode values for each of the feature types.  There may already be a data dictionary somewhere that contains this information.  It can also be derived by selecting unique values from the tables.

**Comment by ahocevar** [comment]
b05e16f09e49b79870951e3fde655abcece81803 implements this on the level of the FType, but if I understand the above correctly we have to change it because the FCodes allowed per layer are relevant, not the FTypes. So what's left to be done is create a list like the layerFTypes, but layerFCodes, and change the store filters in the AttributeForm accordingly.
