### ISSUE TITLE
modifying a feature generates multiple popups

### ISSUE THREAD

**Issue by tschaub** [planetfederal/usgs#98]
At 85edd4e3aa9a83926de113d925c2526b6583903a (e7c9754d1100914e4fc3f1409dc71f36f7e263ab included), when you modify a geometry, additional feature wizards can be opened.  To reproduce, select an existing flowline.  Drag one of the phantom vertices a small amount (less than the click tolerance I imagine).  See a new feature wizard open.

**Comment by tschaub** [comment]
When I rewind [this change](https://github.com/opengeo/gxp/commit/a47244a36e69a1aba4cc956eb7b944739d79161b), the problem goes away.

**Comment by bartvde** [comment]
Okay, with the current state of affairs in gxp (I reverted the change that Tim mentioned here since it was also causing issues for me, and additionally doing in gxp what Tim suggested in #99 so deactivate the select control when an edit popup is open) this does not occur anymore, hence closing this ticket.
